qrpc:
  provider:
    serverAddr: 127.0.0.1:27880
    registryType: nacos
    registryAddr: 127.0.0.1:8848
    registryLoadBalanceType: random
    reflectType: cglib
    heartbeatInterval: -1
    scanNotActiveChannelInterval: -1
    enableCacheResult: true
    cacheResultExpire: 600000
    maxConnectionCount: 3
    disuseStrategyType: strategy_default
    enableRateLimiter: true
    rateLimiterType: counter
    permits: 5
    rateLimiterMilliSeconds: 1000
    rateLimiterFailStrategy: exception
    #服务容错-服务熔断
    enableFusing: true
    fusingStrategyType: counter
    totalFailure: 3
    fusingMilliSeconds: 5000
